name: QT-Console

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install qt make
      run: sudo apt update && sudo apt-get install -y qtcreator qtbase5-dev qt5-qmake cmake
    - name: create make file
      run: cd src && qmake && make
    
      
